"use client";

import { FormEvent, useState } from "react";
import { SiteNav } from "@/components/SiteNav";

export default function ContactPage() {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  return <main className="min-h-screen bg-[#11100f] px-6 pb-24 pt-32 md:px-10 md:pt-44"><SiteNav /><div className="mx-auto grid max-w-[1440px] gap-16 md:grid-cols-12"><div className="md:col-span-5"><p className="eyebrow mb-5">Bookings · Collaborations</p><h1 className="display text-7xl leading-[.85] md:text-[9rem]">Let&apos;s<br />make<br /><i>something.</i></h1><p className="mt-12 max-w-xs text-sm leading-6 text-[#8d8982]">For bookings, representation, or creative collaborations, send a note and the studio will be in touch.</p><div className="mt-10 text-xs leading-6 text-[#bcb7ae]"><p>bookings@maravale.example</p><p>New York · London · Worldwide</p></div></div><div className="md:col-span-5 md:col-start-8">{sent ? <div className="border-t border-white/20 pt-5"><p className="eyebrow">Message received</p><p className="display mt-5 text-5xl">Thank you.<br />We&apos;ll be in touch.</p><button onClick={() => setSent(false)} className="mt-10 border-b border-[#8d8982] pb-1 text-xs uppercase tracking-[.15em]">Send another</button></div> : <form onSubmit={submit} className="space-y-8 border-t border-white/20 pt-5"><label className="block"><span className="eyebrow">Your name</span><input required name="name" className="mt-3 w-full border-b border-white/20 bg-transparent pb-3 text-base outline-none transition-colors focus:border-white" /></label><label className="block"><span className="eyebrow">Email address</span><input required type="email" name="email" className="mt-3 w-full border-b border-white/20 bg-transparent pb-3 text-base outline-none transition-colors focus:border-white" /></label><label className="block"><span className="eyebrow">Inquiry type</span><select name="type" className="mt-3 w-full border-b border-white/20 bg-[#11100f] pb-3 text-base outline-none"><option>Modeling</option><option>Fashion shoot</option><option>Commercial</option><option>Editorial</option><option>Collaboration</option><option>Other</option></select></label><label className="block"><span className="eyebrow">Message</span><textarea required name="message" rows={4} className="mt-3 w-full resize-none border-b border-white/20 bg-transparent pb-3 text-base outline-none focus:border-white" /></label><button className="mt-4 border-b border-white pb-2 text-xs uppercase tracking-[.16em]">Send inquiry ↗</button></form>}</div></div></main>;
}
