"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { works, type Work } from "@/data/work";

export default function AdminPage() {
  const [items, setItems] = useState<Work[]>(works);
  const [saved, setSaved] = useState(false);
  useEffect(() => { const stored = window.localStorage.getItem("mara-works"); if (stored) setItems(JSON.parse(stored)); }, []);
  function toggle(id: number) { setItems((current) => current.map((item) => item.id === id ? { ...item, showOnHome: !item.showOnHome } : item)); setSaved(false); }
  function save() { window.localStorage.setItem("mara-works", JSON.stringify(items)); setSaved(true); }
  return <main className="min-h-screen bg-[#e7e3dc] text-[#171615]"><aside className="fixed bottom-0 left-0 top-0 hidden w-60 border-r border-black/10 p-8 md:block"><Link href="/" className="display text-3xl">Mara Vale</Link><p className="eyebrow mt-16 !text-[#77736d]">Studio admin</p><nav className="mt-8 flex flex-col gap-4 text-sm"><span className="font-medium">Overview</span><span className="text-[#77736d]">Work & gallery</span><span className="text-[#77736d]">Profile</span><span className="text-[#77736d]">Settings</span></nav><Link href="/" className="absolute bottom-8 text-xs text-[#77736d]">← View site</Link></aside><div className="px-6 py-8 md:ml-60 md:px-12 md:py-12"><div className="flex items-start justify-between"><div><p className="eyebrow !text-[#77736d]">Tuesday, September 15</p><h1 className="display mt-3 text-6xl">Good morning.</h1></div><span className="hidden text-xs text-[#77736d] md:block">MARA / ADMIN</span></div><div className="mt-14 grid gap-3 sm:grid-cols-3"><Stat label="Portfolio images" value={String(items.length).padStart(2, "0")} /><Stat label="On homepage" value={String(items.filter((item) => item.showOnHome).length).padStart(2, "0")} /><Stat label="Categories" value="05" /></div><section className="mt-14"><div className="flex items-end justify-between border-b border-black/15 pb-4"><div><p className="eyebrow !text-[#77736d]">Content</p><h2 className="mt-2 text-xl">Homepage selection</h2></div><button onClick={save} className="border-b border-black pb-1 text-xs uppercase tracking-[.14em]">{saved ? "Saved ✓" : "Save changes"}</button></div><p className="mt-4 max-w-lg text-sm leading-6 text-[#77736d]">Choose which published work appears in the homepage edit. This local prototype stores your selection in this browser; connect the same fields to your database and Cloudinary credentials for production.</p><div className="mt-8 divide-y divide-black/10">{items.map((item) => <div key={item.id} className="flex items-center gap-4 py-4"><div className="relative h-16 w-12 overflow-hidden bg-black/10"><img src={item.image} alt="" className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm">{item.title}</p><p className="mt-1 text-xs text-[#77736d]">{item.category} · {item.year}</p></div><button onClick={() => toggle(item.id)} aria-pressed={item.showOnHome} className={`h-6 w-11 rounded-full p-1 transition-colors ${item.showOnHome ? "bg-[#171615]" : "bg-black/15"}`}><span className={`block h-4 w-4 rounded-full bg-[#e7e3dc] transition-transform ${item.showOnHome ? "translate-x-5" : ""}`} /></button><span className="hidden w-20 text-right text-[10px] uppercase tracking-widest text-[#77736d] sm:block">{item.showOnHome ? "Home" : "Hidden"}</span></div>)}</div></section></div></main>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="border border-black/10 p-5"><p className="text-3xl">{value}</p><p className="mt-2 text-xs text-[#77736d]">{label}</p></div>; }
